apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secretmanager
  namespace: xagent-dev
spec:
  provider:
    gcpsm:
      projectID: my-gcp-project
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: external-secrets
