appConfig:
  openai:
    model: gpt-4.1-mini
    embedding_model: text-embedding-3-small
  server:
    host: 0.0.0.0
    port: 8000

secret:
  keys:
    openaiApiKey: OPENAI__API_KEY

externalSecret:
  enabled: true
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secretmanager
  target:
    name: openai-api
  data:
    openaiApiKey:
      key: xagent/prod/langchain-service
      property: OPENAI_API_KEY
