apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "langchain-service.fullname" . }}-config
  labels:
    {{- include "langchain-service.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.appConfig | nindent 4 }}
